theme: jekyll-theme-minimal
encoding: ISO-8859-2
title: Vladimír Krajňák

orcid_id: 0000-0001-6052-7531
google_sch: ac529yMAAAAJ&hl
arxiv_id: 0000-0001-6052-7531 # http://arxiv.org/a/0000-0001-6052-7531.html
researchgate_id: Vladimir-Krajnak
