theme: jekyll-theme-minimal
encoding: ISO-8859-2
title: Vladimír Krajňák

github_username: vkrajnak
ORCID_identifier: 0000-0001-6052-7531
google_scholar_user: ac529yMAAAAJ&hl
arxiv_id: 0000-0001-6052-7531 # http://arxiv.org/a/0000-0001-6052-7531.html
