theme: jekyll-theme-minimal
encoding: ISO-8859-2
title: Vladi Krajňák

linked_in: vladi-krajnak-maths-ai
orcid_id: 0000-0001-6052-7531
google_sch: ac529yMAAAAJ&hl
researchgate_id: Vladimir-Krajnak
arxiv_id: 0000-0001-6052-7531 # http://arxiv.org/a/0000-0001-6052-7531.html
